# Run ansible 'ansible-playbook -K -i inventory playbook.yml --tags 'debug' --extra-vars "user=evgeniy"'

# ansible-playbook -i inventory playbook.yml
# TODO: fix groups https://github.com/weareinteractive/ansible-users-oh-my-zsh/blob/master/tasks/config.yml
# TODO: fix home path to ~{{user_name}}


- name: System provisioning
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    users:
      - name: Evgeniy
        username: "{{ ansible_env.USER }}"
        home: "{{ ansible_env.HOME }}"

  tasks:
    - debug:
        msg: "User name: {{ ansible_env.USER }}"

  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - { role: dotfiles￿ }
    - { role: oh-my-zsh }



# ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"