---

- name: Install Linux apps
  apt: pkg={{ item }} update_cache=true
  with_items:
    # - sublime-text
    - compizconfig-settings-manager
    - unity-tweak-tool
    # - nautilus-dropbox
    - pidgin-otr
    - virtualbox-qt
    - synaptic
    - guake
    - nginx
    - silversearcher-ag
    - markdown
    - gettext
    - editorconfig
    - emacs
    - wget
    - tmux
    - vagrant
    - wine
    - skype
  sudo: yes
  when: is_ubuntu

- name: Install Mac apps
  homebrew_cask: name={{ item }}
  with_items:
    - 1password
    - adium
    - alfred
    - anki
    - dropbox
    - emacs
    - firefox
    - google-chrome
    - google-drive
    - karabiner
    - seil
    - libreoffice
    - mailbox
    - parallels-desktop
    - rescuetime
    - skype
    - mattr-slate
    - sourcetree
    - sublime-text
    - todoist
    - totalterminal
    - transmission
    - vlc
    - vagrant
    - virtualbox
    - webstorm
    - phpstorm
    - atom
    - slack
    - telegram
    - ichm
    - vagrant
    # - xscope
  ignore_errors: true
  sudo: no
  when: is_mac_os

- name: Tmuxinator
  gem: name=tmuxinator
  sudo: yes
