---

- name: Install apps
  apt: pkg={{ item }} update_cache=true
  with_items:
    - sublime-text
    - compizconfig-settings-manager
    - unity-tweak-tool
    - nautilus-dropbox
    - pidgin-otr
    - virtualbox-qt
    - synaptic
    - guake
    - nginx 
    - silversearcher-ag
    - markdown  
    - gettext       
    - editorconfig      
    - emacs
    - wget
    - tmux
  sudo: yes
  when: is_ubuntu

- name: Tmuxinator
  gem: name=tmuxinator
  sudo: yes