---

- name: Load dotfiles
  git: >
       repo=git@bitbucket.org:evgeniy_kazakov/dotfiles.git
       dest=~{{user_name}}/dotfiles
       accept_hostkey=yes
       key_file=~{{user_name}}/.ssh/id_rsa
  sudo: no

- name: Get dotfiles
  shell: 'ls -A ~{{user_name}}/dotfiles'
  register: dotfiles
  sudo: no

- name: Symlink dotfiles
  command: ln -sfF ~{{user_name}}/dotfiles/{{ item }} ~{{user_name}}/
  with_items:
    - .gitignore_global
    - .gitconfig
    - .emacs.d
    - .tmux.conf
    - .tmuxinator
    - .zshrc
    - .zshlogin
    - .slate
  sudo: no

- name: Set dofiles owner
  file: >
        path=~{{user_name}}/dotfiles
        owner={{user_name}}
        group={{user_name}}
        recurse=yes
  when: is_ubuntu