---

# This is a task. Basically, it needs a module command. In this example, it
# also have a `name`, which will be displayed while running the task to give a
# better description of the running task.

- name: update
  apt: update_cache=true

- name: install
  # apt is our module. It installs debian packages. Here we are passing an
  # `` variable, which is the item from `with_items`
  apt: pkg={{ item }} #update_cache=true
  # `with_items` will loop through a list and run the module passing each item
  # as ``
  with_items:
    - zsh
    - tmux
    - git
    - git-core
    - ssh
    - ruby
    - ruby-dev
    - rubygems-integration
    - build-essential
    - curl
    - m4
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev

    - libpcre3 
    - libpcre3-dev
    - openssl
    
    - silversearcher-ag
    - markdown  
    - gettext       
    - wget
    - nginx               
    - editorconfig      
    - nodejs
    - nodejs-legacy
    - npm
    - emacs

  sudo: true

  # for global npm install without sudo
- name: Configure global npm install without sudo
  command: chown -hR evgeniy /usr/local/


- name: Update npm
  command: npm update -g npm


- name: Install n (node version manager)
  npm: name=n global=yes

- name: Update node
  command: n node 0.12.1


# This is an example of how to gather information from the machine. We
# run a command with the "shell" module and register the result into the
# "default_shell" variable
- name: zsh facts
  shell: 'echo $SHELL'
  register: default_shell
  # changed when determines when will this task be considered changed when running
  # ansible. In this case, we want it to always be false, as we are just
  # retrieving information.
  changed_when: False
  sudo: no

# Now, we want to set zsh as the default shell, unless it is already the default
# one.
- name: make zsh default
  command: chsh -s /usr/bin/zsh 
  # This task will run only when the following is true. In here, we check the
  # value registered previously within the "default_shell" variable.
  when: default_shell.stdout.find('/usr/bin/zsh') == -1

- name: Install Oh-my-zsh
  command: git clone git://github.com/robbyrussell/oh-my-zsh.git /home/evgeniy/.oh-my-zsh

- name: Configure Oh-my-zsh
  command: cp /home/evgeniy/.oh-my-zsh/templates/zshrc.zsh-template /home/evgeniy/.zshrc

- name: Compaudit config
  command: compaudit | xargs chmod g-w
