---

# Node and packages

  # for global npm install without sudo
- name: Configure global npm install without sudo
  command: chown -hR {{user_name}}:{{ user_name }} /usr/local/
  when: is_ubuntu

- name: Update npm
  command: npm update -g npm

- name: Install global node modules
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - coffee-script
    - gh
    - grunt-cli
    - gulp
    - httpster
    - jshint
    - jsxhint
    - eslint
    - karma
    - karma-cli
    - n
    - node-inspector
    - nodemon
    - phantomjs
    - tern
    - yo
    - jscs
    - webpack
    - browser-sync
    - browserify
    - jsfmt
    - localtunnel
    - sinopia

- name: Update node
  command: n latest
  sudo: no
